AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'migration/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/StringLiterals:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
